// swift-tools-version: 6.0
import PackageDescription

// Swift integration tests for MyAirtable. This Package.swift is HAND-WRITTEN
// and checked into the repo; it is NOT regenerated by build.sh.
//
// The `MyAirtable` library target points at `output/`, which is the folder
// the code generator writes to (via `--swift-folder`). build.sh resets that
// folder on every build; Package.swift and the Tests/ tree persist.

let package = Package(
    name: "MyAirtable",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
        .watchOS(.v10),
        .tvOS(.v17),
        .visionOS(.v1),
    ],
    products: [
        .library(name: "MyAirtable", targets: ["MyAirtable"])
    ],
    targets: [
        .target(
            name: "MyAirtable",
            path: "output"
        ),
        .testTarget(
            name: "MyAirtableTests",
            dependencies: ["MyAirtable"],
            path: "Tests/MyAirtableTests"
        ),
    ]
)
