// Integration-test harness for the GENERATED Java client.
// The main source set points at output/ — regenerated by ../build.sh; this build file
// and the tests under src/ are hand-written and persist across regenerations.
//
// Version pins match myairtable/tests/java_static (J-F1 decision record):
//   Jackson databind 2.18.2 · JUnit 5 (BOM 5.11.4) · toolchain 21
//
// jackson-datatype-jsr310 is DELIBERATELY absent: its Duration codec would
// shadow AirtableJacksonModule's numeric-seconds codec (java-plan-v2 §2.3.6).

plugins {
    java
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java.srcDir("output")
    }
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.2")

    testImplementation(platform("org.junit:junit-bom:5.11.4"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    useJUnitPlatform()
    // Integration tests hit a real Airtable base: keep classes sequential and
    // surface per-test results in the console.
    systemProperty("junit.jupiter.execution.parallel.enabled", "false")
    testLogging {
        events("passed", "skipped", "failed")
    }
}
