// Integration-test harness for the GENERATED Kotlin client.
// The main source set points at output/ — regenerated by ../build.sh; this build file
// and the tests under src/ are hand-written and persist across regenerations.
//
// Version pins match myairtable/tests/kotlin_static (K-F1 decision record):
//   Kotlin 2.2.20 · kotlinx.serialization 1.9.0 · kotlinx-coroutines 1.10.2 · Ktor 3.2.3

plugins {
    kotlin("jvm") version "2.2.20"
    kotlin("plugin.serialization") version "2.2.20"
}

kotlin {
    jvmToolchain(21)
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        kotlin.srcDir("output")
    }
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    implementation("io.ktor:ktor-client-core:3.2.3")
    implementation("io.ktor:ktor-client-cio:3.2.3")
    implementation("io.ktor:ktor-client-content-negotiation:3.2.3")
    implementation("io.ktor:ktor-serialization-kotlinx-json:3.2.3")

    testImplementation(kotlin("test"))
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
}

tasks.test {
    useJUnitPlatform()
    // Integration tests hit a real Airtable base: keep classes sequential and
    // surface per-test results in the console.
    systemProperty("junit.jupiter.execution.parallel.enabled", "false")
    testLogging {
        events("passed", "skipped", "failed")
    }
}
